apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Atharv22-ak/devops-platform-v1.git
    targetRevision: main
    path: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: devops-practice
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
